language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-25
android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.3
  - android-25
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

script: ./gradlew test